name: Deploy to EC2

on:
  push:
    branches:
      - main
jobs:
  build-development:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build app
      run: npm run build:dev

    - name: Transfer files to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST_DEV }}
        username: ${{ secrets.EC2_USERNAME_DEV }}
        key: ${{ secrets.EC2_PRIVATE_KEY_DEV }}
        source: './*,!./node_modules/*'
        target: '/home/ubuntu/app/'

    - name: Install package and restart app
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.EC2_HOST_DEV }}
        username: ${{ secrets.EC2_USERNAME_DEV }}
        key: ${{ secrets.EC2_PRIVATE_KEY_DEV }}
        port: 22
        script: |
              cd /home/ubuntu/app || { echo "Failed to change directory"; exit 1; }
              /usr/bin/npm install || { echo "npm install failed"; exit 1; }
              /usr/local/bin/pm2 restart 0 || { echo "pm2 restart failed"; exit 1; }
